# Generated by Django 5.1.7 on 2025-03-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importancy',
            field=models.CharField(default='Normal', max_length=12),
            preserve_default=False,
        ),
    ]
