# Generated by Django 5.1.7 on 2025-03-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_importancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importancy',
            field=models.CharField(default='normal', max_length=12),
        ),
    ]
