# Generated by Django 5.1.7 on 2025-03-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_importancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importancy',
            field=models.CharField(max_length=12),
        ),
    ]
