# Generated by Django 5.1.7 on 2025-03-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_task_importancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=30, null=True),
            preserve_default=False,
        ),
    ]
