# Generated by Django 5.1.7 on 2025-03-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_alter_task_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='task_name',
        ),
    ]
